language: python
python: 
  - "3.6"

install: "pip install -r requirements.txt"

script: pytest

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always